version: '3.1'
services:
  web:
    build: .docker
    container_name: blog
    ports:
      - "8181:80"
    volumes:
      - ./:/var/www/html
    external_links:
      - docker-mysql:db
    network_mode: bridge
