version: '3.1'

services:
  web:
    build: .docker
    container_name: cakeblog
    volumes:
      - ./:/var/www/html/public
    ports:
      - "8181:80"
    external_links:
      - docker-mysql:db
    network_mode: bridge
